### ISSUE TITLE
ReImplement Scan Control into frontend

### ISSUE THREAD

**Issue by zainkai** [OSU-CS361-W17/group2_project2#8]
Basically Copy and paste the current design for the fire control then replace any keywords that contain Fire with Scan.

**Comment by Makumasa** [comment]
Working on it now.

**Comment by zainkai** [comment]
With marks permission I implemented the scan feature since he was working on validation and the due date is close.

**Comment by Makumasa** [comment]
Issue ended up being implemented by Kevin, so I instead implemented the error view of our prototype by creating front-end validation for ship placement. Closing the issue seems appropriate.

**Comment by Makumasa** [comment]
For grading reference, the original plan was for me to assign the validation issue to Kevin and him to assign the scan issue to me. We ended up trading tasks shortly afterwards, and so instead of rewriting this issue, we're simply treating is as me assigning it to Kevin.
